name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Extract project version
      id: extract_version
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "PROJECT_VERSION=$version" >> $GITHUB_ENV
      working-directory: javadex

    - name: Build with Maven
      run: mvn clean package
      working-directory: javadex

    - name: Package Javadoc
      run: mvn javadoc:javadoc
      working-directory: javadex

    - name: Create release artifacts
      run: |
        mkdir -p release
        cp javadex/target/*.jar release/
        if ls javadex/target/apidocs/*.jar 1> /dev/null 2>&1; then
          cp javadex/target/apidocs/*.jar release/
        fi
        tar -czvf release/source-code.tar.gz .
        zip -r release/source-code.zip .

    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-artifacts
        path: release/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: JavaDex v${{ env.PROJECT_VERSION }}
        body: |
          Release notes for ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload JAR files to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/
        asset_name: release
        asset_content_type: application/zip